### ISSUE TITLE
cld install fails on Ubuntu

### ISSUE THREAD

**Issue by chuckwilliams37** [dachev/node-cld#19]
UPDATE: Looks like it was a RAM issue - I bumped my Ubuntu server from 512MB to 2G RAM and this seems to have solved it.

This library appears to be a dependency baked deeply into keystonejs (via limax) - so you might have some requests coming. I confirmed that I have node-gyp, build-essentials, make, and python installed.

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty

Error occurs as follows:

    $ npm install cld --save
    -
    > cld@2.4.3 install /home/ubuntu/workspace/MYPROJECT/node_modules/cld
    > node-gyp rebuild
    
    make: Entering directory `/home/ubuntu/workspace/MYPROJECT/node_modules/cld/build'
    CXX(target) Release/obj.target/cld-c/deps/cld/internal/cldutil.o
    CXX(target) Release/obj.target/cld-c/deps/cld/internal/cldutil_shared.o
    CXX(target) Release/obj.target/cld-c/deps/cld/internal/compact_lang_det.o
    CXX(target) Release/obj.target/cld-c/deps/cld/internal/compact_lang_det_hint_code.o
    CXX(target) Release/obj.target/cld-c/deps/cld/internal/compact_lang_det_impl.o
    CXX(target) Release/obj.target/cld-c/deps/cld/internal/debug.o
    CXX(target) Release/obj.target/cld-c/deps/cld/internal/fixunicodevalue.o
    CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_entities.o
    CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_language.o
    CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_ulscript.o
    CXX(target) Release/obj.target/cld-c/deps/cld/internal/getonescriptspan.o
    CXX(target) Release/obj.target/cld-c/deps/cld/internal/lang_script.o
    CXX(target) Release/obj.target/cld-c/deps/cld/internal/offsetmap.o
    CXX(target) Release/obj.target/cld-c/deps/cld/internal/scoreonescriptspan.o
    CXX(target) Release/obj.target/cld-c/deps/cld/internal/tote.o
    CXX(target) Release/obj.target/cld-c/deps/cld/internal/utf8statetable.o
    CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_cjk_uni_prop_80.o
    CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_cjk_compatible.o
    CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_cjk_delta_bi_32.o
    CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_distinct_bi_0.o
    CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_quad0122.o
    g++: internal compiler error: Killed (program cc1plus)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
    make: *** [Release/obj.target/cld-c/deps/cld/internal/cld2_generated_quad0122.o] Error 4
    make: Leaving directory `/home/ubuntu/workspace/MYPROJECT/node_modules/cld/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
    gyp ERR! System Linux 3.14.13-c9
    gyp ERR! command "node" "/home/ubuntu/.nvm/v0.10.35/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/ubuntu/workspace/MYPROJECT/node_modules/cld
    gyp ERR! node -v v0.10.35
    gyp ERR! node-gyp -v v1.0.1
    gyp ERR! not ok 
    
    npm ERR! cld@2.4.3 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the cld@2.4.3 install script.
    npm ERR! This is most likely a problem with the cld package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls cld
    npm ERR! There is likely additional logging output above.
    npm ERR! System Linux 3.14.13-c9
    npm ERR! command "/home/ubuntu/.nvm/v0.10.35/bin/node" "/home/ubuntu/.nvm/v0.10.35/bin/npm" "install" "cld" "--save"
    npm ERR! cwd /home/ubuntu/workspace/MYPROJECT
    npm ERR! node -v v0.10.35
    npm ERR! npm -v 1.4.28
    npm ERR! code ELIFECYCLE
    npm ERR! not ok code 0

**Comment by dachev** [comment]
I wasn't able to reproduce on my Ubuntu 14.04 desktop. It looks like this was caused by insufficient memory. I'm going to close this but feel free to report any new information.

**Comment by lovell** [comment]
We may have run into the GCC memory hog/bug/problem relating to its `track-macro-expansion` feature - see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56746

A possible workaround here might be to add the `-ftrack-macro-expansion=0` flag to [cflags_cc](https://github.com/dachev/node-cld/blob/master/binding.gyp#L14).

**Comment by lovell** [comment]
The 26MB [cld2_generated_quad0122.cc](https://github.com/dachev/node-cld/blob/master/deps/cld/internal/cld2_generated_quad0122.cc) source file is the culprit here.

`-ftrack-macro-expansion=0` shaves about 5% from peak RSS.

If you're compiling on a machine/VM without swap you'll need ~1.2GB of physical RAM. With 1GB swap you might be able to get it to compile with only 512MB physical RAM.

**Comment by lovell** [comment]
Alternatively, the use of `clang` might help reduce compile-time memory consumption.

Running something like `sudo apt-get install clang-3.6` will provide a system-wide install on Ubuntu 14.04.

**Comment by sachss** [comment]
Thank you for your all your assistance, @lovell , and for refactoring this dependency in the latest `limax` build!

**Comment by dachev** [comment]
@sachss @lovell @chuckwilliams37  I just tested with vanilla Ubuntu 14.04 on AWS t2.small and t2.micro and did not see any memory problems. The only hiccup was a gyp error caused by ```'node -e "require('nan')"'``` which fails because the executable name is nodejs.

I've also built on Joyent's free instance which is only 250M.

**Comment by loretoparisi** [comment]
I get the same very error here:

```shell
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-45-virtual
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/node_modules/cld
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 3.2.0-45-virtual
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! cld@2.4.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cld@2.4.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the cld package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls cld
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/npm-debug.log
```

Version is

```
$ lsb_release -d
Description:	Ubuntu 12.04.2 LTS
```

**Comment by sanguinius69** [comment]
Maybe can you provide more of your error log (like the first post from "node-gyp rebuild" line)
Glad to help if I can,

Cheers

**Comment by loretoparisi** [comment]
@sanguinius69 right, maybe it's this


```shell
> node-gyp rebuild

make: Entering directory `/home//node_modules/cld/build'
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cldutil.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cldutil_shared.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/compact_lang_det.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/compact_lang_det_hint_code.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/compact_lang_det_impl.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/debug.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/fixunicodevalue.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_entities.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_language.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_ulscript.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/getonescriptspan.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/lang_script.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/offsetmap.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/scoreonescriptspan.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/tote.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/utf8statetable.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_cjk_uni_prop_80.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_cjk_compatible.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_cjk_delta_bi_32.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_distinct_bi_0.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_quad0122.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_deltaocta0122.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_deltaoctachrome.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_distinctocta0122.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_distinctoctachrome.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_quadchrome_16.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_quadchrome_2.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_score_quad_octa_0122.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_score_quad_octa_2.o
  AR(target) Release/obj.target/deps/cld/cld-c.a
  COPY Release/cld-c.a
  CXX(target) Release/obj.target/cld/src/constants.o
  CXX(target) Release/obj.target/cld/src/cld.o
In file included from ../src/cld.cc:4:0:
../../nan/nan.h:41:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /home/musixmatch/.node-gyp/5.4.1/include/node/node.h:42:0,
                 from ../../nan/nan.h:45,
                 from ../src/cld.cc:4:
/home/musixmatch/.node-gyp/5.4.1/include/node/v8.h:336:1: error: expected unqualified-id before ‘using’
/home/musixmatch/.node-gyp/5.4.1/include/node/v8.h:469:1: error: expected unqualified-id before ‘using’
/home/musixmatch/.node-gyp/5.4.1/include/node/v8.h:856:1: error: expected unqualified-id before ‘using’
In file included from ../../nan/nan.h:194:0,
                 from ../src/cld.cc:4:
../../nan/nan_maybe_43_inl.h:13:1: error: expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:16:1: error: expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:19:12: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:24:12: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:31:1: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:36:1: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:41:1: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:46:1: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:51:1: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:59:1: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:64:12: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:69:12: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:76:12: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:83:12: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:91:12: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:98:1: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:108:12: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:114:12: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:118:12: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:125:1: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:130:1: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:135:1: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:139:12: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:145:12: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:150:12: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:156:12: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:162:12: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:168:12: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:174:12: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:180:12: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:186:12: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:194:12: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:201:1: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:205:12: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:209:12: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:213:12: error: ‘Maybe’ does not name a type
../../nan/nan_maybe_43_inl.h:217:12: error: ‘MaybeLocal’ does not name a type
../../nan/nan_maybe_43_inl.h:223:12: error: ‘MaybeLocal’ does not name a type
In file included from ../../nan/nan.h:199:0,
                 from ../src/cld.cc:4:
../../nan/nan_converters.h:14:11: error: ‘MaybeLocal’ does not name a type
../../nan/nan_converters.h:16:56: error: ‘Maybe’ does not name a type
../../nan/nan_converters.h:26:1: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:27:1: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:28:1: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:29:1: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:30:1: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:31:1: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:32:1: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:42:1: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:43:1: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:44:1: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:45:1: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:46:1: error: ‘return_t’ does not name a type
In file included from ../../nan/nan_converters.h:59:0,
                 from ../../nan/nan.h:199,
                 from ../src/cld.cc:4:
../../nan/nan_converters_43_inl.h:18:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<v8::Boolean>’ does not name a type
../../nan/nan_converters_43_inl.h:19:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<v8::Number>’ does not name a type
../../nan/nan_converters_43_inl.h:20:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<v8::String>’ does not name a type
../../nan/nan_converters_43_inl.h:21:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<v8::Object>’ does not name a type
../../nan/nan_converters_43_inl.h:22:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<v8::Integer>’ does not name a type
../../nan/nan_converters_43_inl.h:23:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<v8::Uint32>’ does not name a type
../../nan/nan_converters_43_inl.h:24:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<v8::Int32>’ does not name a type
../../nan/nan_converters_43_inl.h:34:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<bool>’ does not name a type
../../nan/nan_converters_43_inl.h:35:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<double>’ does not name a type
../../nan/nan_converters_43_inl.h:36:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<long int>’ does not name a type
../../nan/nan_converters_43_inl.h:37:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<unsigned int>’ does not name a type
../../nan/nan_converters_43_inl.h:38:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<int>’ does not name a type
In file included from ../../nan/nan.h:200:0,
                 from ../src/cld.cc:4:
../../nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Integer]’:
../../nan/nan_new.h:21:32: error: no matching function for call to ‘To(v8::Local<v8::Integer>&)’
../../nan/nan_new.h:21:32: note: candidate is:
../../nan/nan_converters.h:53:38: note: template<class T> typename Nan::imp::ToFactory::return_t Nan::To(v8::Local<v8::Value>)
../../nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Int32]’:
../../nan/nan_new.h:28:30: error: no matching function for call to ‘To(v8::Local<v8::Integer>&)’
../../nan/nan_new.h:28:30: note: candidate is:
../../nan/nan_converters.h:53:38: note: template<class T> typename Nan::imp::ToFactory::return_t Nan::To(v8::Local<v8::Value>)
../../nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Uint32]’:
../../nan/nan_new.h:35:31: error: no matching function for call to ‘To(v8::Local<v8::Integer>&)’
../../nan/nan_new.h:35:31: note: candidate is:
../../nan/nan_converters.h:53:38: note: template<class T> typename Nan::imp::ToFactory::return_t Nan::To(v8::Local<v8::Value>)
../../nan/nan_new.h: At global scope:
../../nan/nan_new.h:43:11: error: ‘MaybeLocal’ does not name a type
../../nan/nan_new.h:75:17: error: ‘return_t’ does not name a type
../../nan/nan_new.h:141:17: error: ‘return_t’ does not name a type
../../nan/nan_new.h:147:17: error: ‘return_t’ does not name a type
../../nan/nan_new.h:148:17: error: ‘return_t’ does not name a type
../../nan/nan_new.h:160:17: error: ‘return_t’ does not name a type
../../nan/nan_new.h:161:17: error: ‘return_t’ does not name a type
../../nan/nan_new.h:162:17: error: ‘return_t’ does not name a type
../../nan/nan_new.h:163:17: error: ‘return_t’ does not name a type
../../nan/nan_new.h:165:17: error: ‘return_t’ does not name a type
../../nan/nan_new.h:166:17: error: ‘return_t’ does not name a type
../../nan/nan_new.h:182:17: error: ‘return_t’ does not name a type
../../nan/nan_new.h:183:17: error: ‘return_t’ does not name a type
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:200,
                 from ../src/cld.cc:4:
../../nan/nan_implementation_12_inl.h:56:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::Date>’ does not name a type
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::Function>::return_t Nan::imp::Factory<v8::Function>::New(Nan::FunctionCallback, v8::Local<v8::Value>)’:
../../nan/nan_implementation_12_inl.h:90:46: error: ‘NewInstance’ was not declared in this scope
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::FunctionTemplate>::return_t Nan::imp::Factory<v8::FunctionTemplate>::New(Nan::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>)’:
../../nan/nan_implementation_12_inl.h:118:48: error: ‘NewInstance’ was not declared in this scope
../../nan/nan_implementation_12_inl.h: At global scope:
../../nan/nan_implementation_12_inl.h:197:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::RegExp>’ does not name a type
../../nan/nan_implementation_12_inl.h:216:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::Script>’ does not name a type
../../nan/nan_implementation_12_inl.h:222:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::Script>’ does not name a type
../../nan/nan_implementation_12_inl.h:254:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:262:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:268:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:275:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:281:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:286:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:347:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::UnboundScript>’ does not name a type
../../nan/nan_implementation_12_inl.h:354:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::UnboundScript>’ does not name a type
In file included from ../../nan/nan.h:200:0,
                 from ../src/cld.cc:4:
../../nan/nan_new.h:293:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:299:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:305:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:311:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:317:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:323:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:329:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:335:1: error: ‘return_t’ in ‘struct Nan::imp::Factory<v8::RegExp>’ does not name a type
In file included from ../src/cld.cc:4:0:
```

**Comment by dachev** [comment]
@loretoparisi What's your g++ version?

**Comment by loretoparisi** [comment]
@dachev 

```shell
macbookproloreto:collection admin$ g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
macbookproloreto:co
```

**Comment by dachev** [comment]
@loretoparisi The original error you shower occurred on Ubuntu 12.04

**Comment by loretoparisi** [comment]
@dachev This is my machine

```
$ lsb_release -d
Description:    Ubuntu 12.04.2 LTS
```

running on Windows Azure btw.

**Comment by dachev** [comment]
Right. What is the g++ version on the device that failed to install node?

**Comment by loretoparisi** [comment]
@dachev I'm using `Apple LLVM version 7.0.2 (clang-700.1.81)` - see above for details.

**Comment by dachev** [comment]
@loretoparisi I am lost. From your initial comment it seemed like the module failed to build on Ubuntu 12.04.2.

**Comment by loretoparisi** [comment]
@dachev you are right, sorry, here you are:

```
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --disable-werror --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) 
```

**Comment by dachev** [comment]
@loretoparisi The latest CLD version requires g++ 4.8 to build. You can either install the previous CLD version (2.4.4) or upgrade g++. Personally, I would go with 2.4.4

**Comment by loretoparisi** [comment]
@dachev thank you downgraded to `2.4.4` for now.
